os: linux

services:
- docker

archlinux:
  repos:
  - papyros=http://dash.papyros.io/repos/$repo/$arch
  packages:
    - base
    - base-devel
  # pacman packages

  script:
  - "sh build.sh"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
