os: linux

services:
- docker

archlinux:
  packages:
    - base
    - base-devel
  # pacman packages
  before_install:
  - "sudo localectl set-locale LANG=en_US.UTF-8"
  - "unset LANG; source /etc/profile.d/locale.sh"
  script:
  - "sh build.sh"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
