name: build-zen
on: [push, pull_request]

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Arch Linux package
      - uses: the-ashh/build-aur-action@master
